create table candidate
(
    id                       bigint generated by default as identity
        primary key,
    created_at               timestamp(6),
    updated_at               timestamp(6),
    address                  text,
    birth_date               date         not null,
    city                     varchar(100),
    country                  varchar(100) not null,
    cv_file                  varchar(255),
    education_level          varchar(100),
    email                    varchar(150) not null
        constraint ukqfut8ruekode092nlkipgl09g
            unique,
    first_name               varchar(100) not null,
    last_degree              varchar(150),
    last_name                varchar(100) not null,
    motivational_letter_file varchar(255),
    phone                    varchar(20),
    skills                   text,
    years_experience         integer      not null
);

alter table candidate
    owner to postgres;

create table department
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    annual_budget double precision,
    description   text,
    name          varchar(100) not null
        constraint uk1t68827l97cwyxo9r1u6t4p7d
            unique
);

alter table department
    owner to postgres;

create table job
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    description     text,
    required_degree text,
    required_skills text,
    title           varchar(100) not null,
    department_id   bigint       not null
        constraint fkhn4ysm8p7xteitn89lhj5c3g7
            references department
);

alter table job
    owner to postgres;

create table employee
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    address           text,
    base_salary       double precision not null,
    birth_date        date             not null,
    city              varchar(100),
    contract_end_date date,
    country           varchar(100)     not null,
    employee_number   varchar(50)      not null
        constraint ukoosi3suv54trvclvanif87cnt
            unique,
    first_name        varchar(100)     not null,
    gender            varchar(1),
    hire_date         date             not null,
    last_name         varchar(100)     not null,
    work_email        varchar(150)     not null
        constraint uk3kqyqd3xajmmrmv7pvu33nfvf
            unique,
    work_phone        varchar(20),
    job_id            bigint           not null
        constraint fk3qan7dnbwrvqngcqup9h9a1tt
            references job
);

alter table employee
    owner to postgres;

create table employment_contract
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    annual_bonus      double precision,
    annual_leave_days integer          not null,
    benefits          text,
    contract_file     varchar(255),
    contract_number   varchar(100)     not null
        constraint ukjwglx0jn2stf3ystcxhjk74s0
            unique,
    end_date          date,
    gross_salary      double precision,
    signature_date    date,
    start_date        date             not null,
    weekly_hours      double precision not null,
    employee_id       bigint           not null
        constraint ukevbw7br3pw0phqhrxahijvo6a
            unique
        constraint fk9l8m43d71ay4j0wivy7ue6a80
            references employee
);

alter table employment_contract
    owner to postgres;

create table publication
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    closing_date        date,
    description         text         not null,
    number_of_positions integer      not null,
    published_date      date         not null,
    status              varchar(50)  not null,
    title               varchar(200) not null,
    job_id              bigint       not null
        constraint fk5hgddrqfhxo21wdu05ocrme80
            references job
);

alter table publication
    owner to postgres;

create table qcm
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    description      text,
    duration_minutes integer,
    required_score   double precision,
    title            varchar(150) not null,
    total_score      double precision
);

alter table qcm
    owner to postgres;

create table application
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    applied_at     timestamp(6) not null,
    comment        text,
    document_score double precision,
    score          double precision,
    status         varchar(50)  not null,
    candidate_id   bigint       not null
        constraint uksht7wyh4pby72irlxhiurtuo9
            unique
        constraint fkgj6l06j10b3sv83rvsnmei78a
            references candidate,
    publication_id bigint
        constraint fkb20odsgculmq1rko745qgab49
            references publication,
    qcm_id         bigint
        constraint fkajo1vq5mj9u3nt1p62urpe3om
            references qcm
);

alter table application
    owner to postgres;

create table attempt
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    obtained_score double precision,
    application_id bigint not null
        constraint ukgnlm4w212kvvtrne1ybcu240l
            unique
        constraint fkryd25jyb7vk00iaakamnyfdqv
            references application
);

alter table attempt
    owner to postgres;

create table interview
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    duration_minutes integer,
    end_time         time(6),
    interview_date   date        not null,
    interview_type   varchar(50) not null,
    report           text,
    score            double precision,
    start_time       time(6)     not null,
    application_id   bigint      not null
        constraint uklt6bbaeunkw0xckuy0j6u97bk
            unique
        constraint fkdyrt85lva791fmh1qnhf0ee0f
            references application,
    interviewer_id   bigint      not null
        constraint fk245o6oixt4ooh4oqtowq7tdox
            references employee,
    comment          text,
    location         text,
    status           varchar(50) not null,
    candidate_id     bigint      not null
        constraint fkjod0wwyxvbi7qyx9cmlnt8xq4
            references candidate
);

alter table interview
    owner to postgres;

create table question
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    libelle    varchar(150) not null,
    required   boolean,
    score      double precision,
    qcm_id     bigint       not null
        constraint fkersjmr6aywd7fhaxnu5l8uibj
            references qcm
);

alter table question
    owner to postgres;

create table choice
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    correct     boolean,
    libelle     varchar(150) not null,
    question_id bigint       not null
        constraint fkcaq6r76cswke5b9fk6fyx3y5w
            references question
);

alter table choice
    owner to postgres;

create table answer
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    attempt_id bigint not null
        constraint fkdpscndk449bfrihj6xw972qs9
            references attempt,
    choice_id  bigint not null
        constraint fk87jfa0drr2wricwtg8pdab2na
            references choice
);

alter table answer
    owner to postgres;

create table token
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    active          boolean not null,
    expiration_date timestamp(6),
    value           varchar(255),
    application_id  bigint
        constraint ukmbbw4fbq9plu2rrkdbwmlnu9s
            unique
        constraint fko7mcnnocpbebrna4a0eaqqniq
            references application
);

alter table token
    owner to postgres;

create table staffing_need
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    budget_allocated    numeric(15, 2),
    description         text,
    justification       text,
    number_of_positions integer      not null,
    priority            varchar(50),
    required_start_date date,
    status              varchar(50)  not null,
    title               varchar(200) not null,
    department_id       bigint       not null
        constraint fkbifv1usdbut8g7uyd9lexsmyv
            references department,
    job_id              bigint       not null
        constraint fkq7y69sefiscmyd2iyvipamucw
            references job,
    requested_by        bigint
        constraint fku13ri7obcsiy1hyw70mywpsn
            references employee
);

alter table staffing_need
    owner to postgres;

